apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpress-namespace
data:
  WORDPRESS_DB_HOST: {{ .Values.wordpress.db.host }}
  WORDPRESS_DB_NAME: {{ .Values.wordpress.db.name }}
  WORDPRESS_DB_USER: {{ .Values.wordpress.db.user }}