apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wordpress-namespace
spec:
  type: {{ .Values.wordpress.service.type }}
  ports:
  - port: {{ .Values.wordpress.service.port }}
    targetPort: 80
    nodePort: {{ .Values.wordpress.service.nodePort }}
  selector:
    app: wordpress