apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "wordpress.fullname" . }}
  namespace: wordpress-namespace
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "wordpress.fullname" . }}
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
        {{- include "wordpress.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: wordpress
          image: {{ .Values.wordpress.image }}
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - configMapRef:
                name: wordpress-config
            - secretRef:
                name: wordpress-secret
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.wordpress.db.host }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.wordpress.db.name }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.wordpress.db.user }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.wordpress.db.password }}
  volumeClaimTemplates:
    - metadata:
        name: wordpress-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: csi-cinder-high-speed
